### ISSUE TITLE
Populate Better Explanations milestone

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#188]
Although I'm still a little way away from finishing the [Unsupervised Play-testing](https://github.com/ctm/mb2-doc/milestone/1) milestone, I've been thinking for a while about various things that simply need some better wording, or in some cases just a small amount of changes to the UI.

This issue is a meta-issue for doing a brain dump and creating individual issues for the various things I've already been thinking about. The first step is to figure out my various audiences, including, but not limited to:

- [x] existing players (#579, #580)
- [x] potential players who are on the fence (#581)
- [x] people who have approached me about their home games (#582)
- [x] BARGE organizers (#583)
- [x] people who receive shareable links (#82)
- [x] friends-and-family investors (#584)
- [x] potential kickstarter participants ([milestone](https://github.com/ctm/mb2-doc/milestone/6))
- [x] potential crowdfunding portal investors (#587)
- [x] people who know me through Team RWB (#581, #588)
- [x] people who know me through AGDG (#589,  #590)
- [x] people who know me from ARDI (#589, #591)
- [x] people who know me through running (#589, #592)
- [x] deadheads (#589, #593)

There's so much low-hanging UI fruit that it's hard not to spend all my time gathering it. However, to some extent I've starved various issues that in the medium-run will allow me to develop mb2 and craftpoker.com a lot quicker. Some of that has been due to covid-19 and various knock-on effects, but it's time to look one milestone ahead and pick the low-hanging fruit that is just a matter of exposing things that already exist (both pre-existing functionality as well as the overall business plan).

So, the idea is for this milestone to consist of a bunch of super small issues that when completed will actively encourage people to share urls, because they know that the recipient will be provided enough information to see what's going on and how to participate (be it becoming a player or just cheering a player on).

**Comment by ctm** [comment]
I'll probably have more issues to add in the future, but I have the big bases covered.
