### ISSUE TITLE
WSOP-style tournament series

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#971]
Set up, announce and run a daily series of WSOP-style tournaments.

- [x] Choose the structures for each day (Dan did this for me. Thanks, Dan!)
- [x] Implement the first few structures
- [x] Scan ahead for problems
- [x] Choose time(s): 3pm Pacific
- [x] Decide round duration: 5 minutes (but eventually with a soft cap on total duration)
- [x] Create a tag
- [x] Add first few days of tournaments
- [x] Add a placeholder WSOPS section to [Players' Manual](https://ctm.github.io/docs/players_manual/)
- [x] Announce on the BARGE list
- [x] Expand the WSOPS section to include all the details
- [x] Update craftpoker.com to mention the WSOPS series
- [x] Get tournaments set up through Sunday, June 19th
  - [x] Wednesday, June 15th: HORSE
  - [x] Thursday, June 16th: Seven Card Stud Hi-Lo 8 or Better
  - [x] Friday, June 17th: Millionaire Maker No-Limit Hold'em
  - [x] Saturday, June 18th: Pot-Limit Omaha 6-Handed
  - [x] Sunday, June 19th: Super Bounty No-Limit Hold'em
- [x] Add the mix structures, since those are mixes that aren't currently offered
  - [x] [Allow per-game stakes](https://github.com/ctm/mb2-doc/issues/189)
  - [x] Wednesday, June 22nd: Eight Game Mix
  - [x] Friday, June 24th: Nine Game Mix
  - [x] Sunday, June 26th: Poker Players Championship
- [x] Add the remaining (and easier!) structures through June 25th
  - [x] Monday, June 20th: Freezeout No-Limit Hold'em
  - [x] Tuesday, June 21st: #&#x2060;45 Pot-Limit Omaha
  - [x] Thursday, June 23rd: #&#x2060;49 No-Limit Hold'em
  - [x] Saturday, June 25th: Mixed No-Limit Hold'em and Pot-Limit Omaha
- [x] Get tournaments set up through Sunday, June 26th (see above)
- [x] [Support all-ante, no-blinds Hold'em](https://github.com/ctm/mb2-doc/issues/976)
- [x] Add the remaining structures
  - [x] Monday, June 27th: Deep Stack Championship
  - [x] Tuesday, June 28th: Short Deck No-Limit Hold'em
  - [x] Wednesday, June 29th: Pot-Limit Omaha Hi-Lo 8 or Better Championship
  - [x] Thursday, June 30th: Pot-Limit Omaha Deep Stack
  - [x] Friday, July 1st: Super Turbo Bounty No-Limit Hold'em
  - [x] Saturday, July 2nd: Pot-Limit Omaha Championship
  - [x] Sunday, July 3rd: Main Event No-Limit Hold'em Championship
- [x] Get remaining tournaments set up (see above)
- [x] [Simplify the login page](https://github.com/ctm/mb2-doc/issues/981)
- [x] Spread the word
- [x] [Provide a count of observers](https://github.com/ctm/mb2-doc/issues/977)
- [x] Encourage others to spread the word
- [x] Get rebuy functionality in place
  - [x] [Make rebuys affect leaderboard standings](https://github.com/ctm/mb2-doc/issues/662)
  - [x] [Enforce rebuy cap](https://github.com/ctm/mb2-doc/issues/985)
  - [x] [Make sure rebuy gives lammers when appropriate.](https://github.com/ctm/mb2-doc/issues/988)
  - [x] [Fix so player can rebuy on bust in hand that starts in rebuy period](https://github.com/ctm/mb2-doc/issues/989)
  - [x] [Make rebuy info available from the lobby](https://github.com/ctm/mb2-doc/issues/203)
  - [x] [Announce, or otherwise make available at the table, the end of the rebuy period](https://github.com/ctm/mb2-doc/issues/703)

Previously the above list included [getting trophies ordered](https://github.com/ctm/mb2-doc/issues/990) and implementing [duration soft-caps](https://github.com/ctm/mb2-doc/issues/969). I've taken the off this issue and put them into their own issues so I can close this issue. This issue grew to contain a ton of programming related checkboxes and those are all done now. In theory the series can run in my absence and as such, I think closing this issue makes sense. Getting trophies ordered, however is super high priority. Adding a duration soft-cap is not yet needed though :-(

**Comment by ctm** [comment]
These will be the structures:




|Date | Event |
|--|--|
|11-Jun | 6-handed Limit Hold 'em |  
|12-Jun | NLHE Deep Stack |  
|13-Jun | No Limit 2-7 Lowball |  
|14-Jun | PLO 8-handed |  
|15-Jun | HORSE |  
|16-Jun | Stud High/Low 8 or better |  
|17-Jun | NLHE (Millionaire Maker) |  
|18-Jun | 6-handed PLO |  
|19-Jun | Super Turbo Bounty NLHE |  
|20-Jun | NLHE |  
|21-Jun | PLO 8-handed |  
|22-Jun | 6-handed 8-Game Mix |  
|23-Jun | NLHE |  
|24-Jun | 6-handed 9-Game Mix |  
|25-Jun | 8-handed Mixed NLHE-PLO |  
|26-Jun | Poker Players Championship |
|27-Jun | Deepstack Championship |  
|28-Jun | Short Deck NLHE |  
|29-Jun | PLO/8 Championship |  
|30-Jun | PLO Deep Stack |  
|1-Jul | Super Turbo Bounty NLHE |  
|2-Jul | 8-handed PLO Championship
|3-Jul | Main Event|

<br class="Apple-interchange-newline">

**Comment by ctm** [comment]
I'm checking "Spread the word" and "Encourage others to spread the word", but I plan on continuing to do both in my "copious" spare time. I am hoping to get soft duration caps done today or tomorrow and get the rebuy issues done on Monday, but I've fallen behind on the business side&hellip;

**Comment by ctm** [comment]
Oh and I am hoping to get the first of a few orders in to trophies2go on Monday.

**Comment by ctm** [comment]
Since we're not yet getting enough players to need the soft duration cap, I'm going to work on rebuys today and then work on the soft duration cap after they're in place.

**Comment by ctm** [comment]
I did a fairly large refactor that introduces `LevelNumber` and `RoundIndex` newtypes to replace `u8` so it can always be clear whether we're talking about levels (which don't include breaks) or rounds (which do).

That refactor ate my entire day yesterday, but I'm still hopeful that I'll have rebuys turned on for this evening's WSOP-Style tournament. To make that more likely, I'm doing the most annoying part first (dealing with the database and associated bookkeeping). Once I get that working, I'll deploy and work on implementing the cap.

It seems unlikely that I'll get the bookkeeping done but not the cap, but if that happens, I can just ask the players to voluntarily limit themselves to one rebuy (because that's what the structure sheet has).
